/// Loom: a model-to-RTL compiler. Parses LLM model files into a typed IR and
/// lowers them to Harbor/ROHD accelerator IP.
library;

export 'src/config/config.dart';
export 'src/ir/model_graph.dart';
export 'src/ir/tensor.dart';
export 'src/frontend/hf_config.dart';
export 'src/frontend/gguf_names.dart';
export 'src/frontend/gguf_config.dart';
export 'src/frontend/gguf_tokenizer.dart';
export 'src/frontend/model_source.dart';
export 'src/weights/weight_store.dart';
export 'src/weights/safetensors.dart';
export 'src/weights/sharded_safetensors.dart';
export 'src/weights/gguf.dart';
export 'src/weights/llama2c.dart';
export 'src/weights/flash_image.dart';
export 'src/weights/binding.dart';
export 'src/golden/ops.dart';
export 'src/golden/quant.dart';
export 'src/golden/attention.dart';
export 'src/golden/runner.dart';
export 'src/golden/metrics.dart';
export 'src/golden/generate.dart';
export 'src/golden/gptq.dart';
export 'src/golden/svd.dart';
export 'src/golden/moe.dart';
export 'src/golden/mtp.dart';
export 'src/golden/vision.dart';
export 'src/golden/projector.dart';
export 'src/tokenizer/bpe_tokenizer.dart';
export 'src/tokenizer/llama2c_tokenizer.dart';
export 'src/hw/dummy.dart';
export 'src/hw/controller.dart';
export 'src/hw/pe_array.dart';
export 'src/hw/requantize.dart';
export 'src/hw/vector_unit.dart';
export 'src/hw/matmul.dart';
export 'src/hw/linear.dart';
export 'src/hw/accelerator.dart';
export 'src/hw/wb_reader.dart';
export 'src/hw/stream_matmul.dart';
export 'src/hw/stream_accelerator.dart';
export 'src/hw/fp_residual.dart';
export 'src/hw/fp_recip.dart';
export 'src/hw/fp_rmsnorm.dart';
export 'src/hw/fp_silu.dart';
export 'src/hw/fp_softmax.dart';
export 'src/hw/fp_rope.dart';
export 'src/hw/fp_mac.dart';
export 'src/hw/attention_head.dart';
export 'src/hw/act_quant.dart';
export 'src/hw/dequant.dart';
export 'src/hw/fp_linear.dart';
export 'src/hw/fp_linear_accelerator.dart';
export 'src/hw/linear_seq.dart';
export 'src/hw/norm_linear.dart';
export 'src/hw/attn_seq.dart';
export 'src/hw/qkv_norm.dart';
export 'src/hw/mlp_seq.dart';
export 'src/hw/rope_vec.dart';
export 'src/runtime/half.dart';
export 'src/runtime/loom_device.dart';
export 'src/runtime/fp_linear_runner.dart';
export 'src/runtime/serial_link.dart';
export 'src/nano/nano_model.dart';
export 'src/hw/usb_bridge.dart';
export 'src/hw/usb_device.dart';
export 'src/hw/uart_bridge.dart';

/// Library version string (used by the smoke test and `--version`).
const String loomVersion = '0.0.1';
