// The streaming memory-backed-matmul SoC built as a real HarborSoC: UART host
// bridge + LoomStreamAccelerator (DUAL ROLE: CSR slave peripheral AND weight-
// read master) + HarborSram, wired by HarborSoC.buildFabric (auto-arbiter for
// the two masters). Generation is fully Harbor-driven and target-parameterized
// (no hand-written SV, no hardcoded ECP5).

import 'dart:io';

import 'package:harbor/harbor.dart';
import 'package:rohd/rohd.dart';
import 'package:test/test.dart';

import '../../bin/loom_genip.dart'
    show buildLoomSoc, LoomTransport, StreamDatapath;

HarborFpgaTarget _ecp5() => HarborFpgaTarget.ecp5(
  device: '25f',
  package: 'CSFBGA285',
  frequency: 48000000,
);

void main() {
  tearDown(() async {
    await Simulator.reset();
  });

  test(
    'streaming SoC composes as a HarborSoC and emits all submodules',
    () async {
      final soc = buildLoomSoc(
        name: 'LoomStreamSoC',
        transport: LoomTransport.uart,
        datapath: const StreamDatapath(),
      );
      await soc.build();
      final sv = soc.generateSynth();
      expect(sv, contains('LoomStreamAccelerator'));
      expect(sv, contains('LoomStreamMatmul'));
      expect(sv, contains('LoomUartBridge'));
      expect(sv, contains('HarborSram'));
      expect(sv, contains('WishboneArbiter_M2')); // 2 masters -> auto-arbiter
      expect(sv, contains('WishboneDecoder'));
    },
  );

  test(
    'Harbor generates the full target-specific flow (ECP5, no hand-written SV)',
    () async {
      final soc = buildLoomSoc(
        name: 'LoomStreamSoC',
        transport: LoomTransport.uart,
        target: HarborFpgaTarget.ecp5(
          device: '25f',
          package: 'CSFBGA285',
          frequency: 48000000,
        ),
        datapath: const StreamDatapath(),
      );
      final dir = Directory.systemTemp.createTempSync('loom_stream_soc_');
      try {
        await soc.generateAll(dir);
        expect(File('${dir.path}/filelist.f').existsSync(), isTrue);
        expect(
          File('${dir.path}/LoomStreamSoC.lpf').existsSync(),
          isTrue,
          reason: 'ECP5 constraints generated by Harbor',
        );
        expect(File('${dir.path}/synth.tcl').existsSync(), isTrue);
        expect(File('${dir.path}/Makefile').existsSync(), isTrue);
        expect(Directory('${dir.path}/rtl').listSync().isNotEmpty, isTrue);
      } finally {
        dir.deleteSync(recursive: true);
      }
    },
  );

  test(
    'FPGA target uses internal POR: flashable from clk + UART (no reset pin)',
    () async {
      final soc = buildLoomSoc(
        name: 'LoomStreamSoC',
        transport: LoomTransport.uart,
        target: HarborFpgaTarget.ecp5(
          device: '25f',
          package: 'CSFBGA285',
          frequency: 48000000,
        ),
        datapath: const StreamDatapath(),
      );
      await soc.build();
      expect(soc.tryInput('clk'), isNotNull);
      expect(soc.tryInput('uart_rx'), isNotNull);
      expect(soc.tryOutput('uart_tx'), isNotNull);
      // Internal power-on reset -> NO external reset pin to wire on the board.
      expect(
        soc.tryInput('reset'),
        isNull,
        reason: 'internal POR, no reset pin',
      );
    },
  );

  test(
    'weights-in-DDR variant composes with HarborDdrController + SDRAM pads',
    () async {
      final soc = buildLoomSoc(
        name: 'LoomStreamSoC',
        transport: LoomTransport.uart,
        target: _ecp5(),
        datapath: const StreamDatapath(weightsInDdr: true),
      );
      await soc.build();
      final sv = soc.generateSynth();
      expect(sv, contains('HarborDdrController'));
      expect(sv, contains('LoomStreamAccelerator'));
      // SDRAM pads brought to the SoC top (dq/dqs/dqs_n are inout).
      expect(soc.tryOutput('sdram_addr'), isNotNull);
      expect(soc.tryInOut('sdram_dq'), isNotNull);
      expect(soc.tryInOut('sdram_dqs'), isNotNull);
      expect(soc.tryOutput('sdram_cs_n'), isNotNull);
    },
  );

  test(
    'same SoC retargets to Spartan-7 (Xilinx .xdc) with no code change',
    () async {
      final soc = buildLoomSoc(
        name: 'LoomStreamSoC',
        transport: LoomTransport.uart,
        target: HarborFpgaTarget.spartan7(device: 'xc7s50', package: 'csga324'),
        datapath: const StreamDatapath(),
      );
      final dir = Directory.systemTemp.createTempSync('loom_stream_soc_s7_');
      try {
        await soc.generateAll(dir);
        expect(
          File('${dir.path}/LoomStreamSoC.xdc').existsSync(),
          isTrue,
          reason: 'Xilinx constraints generated by Harbor',
        );
      } finally {
        dir.deleteSync(recursive: true);
      }
    },
  );
}
